"""Generate docs/validation.md from results/*.json (BRIEF.md section 8).

    python -m treesvb.validate          # rewrite docs/validation.md
    python -m treesvb.validate --check  # fail if the committed file is out of date

Every number in the document is read from a result file; nothing is typed by hand.
"""

from __future__ import annotations

import argparse
import json
import sys

from .results import REPO, RESULTS

DOC = REPO / "docs" / "validation.md"


def _load(rel: str) -> dict | None:
    p = RESULTS / rel
    return json.loads(p.read_text()) if p.exists() else None


def _pct(v: float, digits: int = 2) -> str:
    return f"{100 * v:.{digits}f}%"


def _sci(v: float) -> str:
    return f"{v:.1e}"


def _verdict(r: dict | None) -> str:
    if r is None:
        return "not yet computed"
    return "meets the target" if r["passed"] else "**misses the target**"


def _provenance(r: dict) -> str:
    return (
        f"_Source: `results/{r['_path']}`, generated {r['generated_at']} by "
        f"`{r['generated_by']}` at commit `{r['commit'][:7]}`._"
    )


def _section(title: str, r: dict | None, body: list[str]) -> list[str]:
    out = [f"### {title}", "", f"Verdict: {_verdict(r)}.", ""]
    if r is None:
        return [*out, "Not yet computed.", ""]
    if r.get("method"):
        out += [f"Method: {r['method']}.", ""]
    out += body
    out += ["", _provenance(r), ""]
    return out


def render() -> str:
    def load(rel):
        r = _load(rel)
        if r is not None:
            r["_path"] = rel
        return r

    lines = [
        "# Validation",
        "",
        "Generated by `python -m treesvb.validate` from `results/*.json`. Do not edit by hand; "
        "rerun the command after the results change. Every model number here is simulated.",
        "",
        "## 1. Solver benchmarks",
        "",
    ]

    r = load("benchmarks/poiseuille.json")
    body = []
    if r:
        body = [
            f"Target: relative L2 error below {_pct(r['threshold']['rel_l2_below'], 0)} with "
            f"{r['threshold']['for_height_at_least']} cells across or more.",
            "",
            "| Cells across | Relative L2 error | Steps |",
            "| --- | --- | --- |",
            *[f"| {x['height']} | {_pct(x['rel_l2'], 3)} | {x['steps']} |" for x in r["rows"]],
            "",
            f"Observed order of convergence: {r['observed_order']:.2f}.",
        ]
    lines += _section("Channel flow against the exact Poiseuille profile", r, body)

    for re in (100, 1000):
        r = load(f"benchmarks/cavity_re{re}.json")
        body = []
        if r:
            cu, cv = r["u_vertical_centreline"], r["v_horizontal_centreline"]
            body = [
                f"Target: within {_pct(r['threshold']['max_abs_error_below'], 0)} of the lid "
                f"speed at every tabulated point. Grid {r['grid']} x {r['grid']}, "
                f"{r['steps']} steps.",
                "",
                "| Profile | Largest difference | RMS difference |",
                "| --- | --- | --- |",
                f"| u on the vertical centreline | {_pct(cu['max_abs_error'])} | "
                f"{_pct(cu['rms_error'])} |",
                f"| v on the horizontal centreline | {_pct(cv['max_abs_error'])} | "
                f"{_pct(cv['rms_error'])} |",
                "",
                f"Reference: {r['reference']['citation']}; values via "
                f"{r['reference'][f're{re}_via']}.",
            ]
        lines += _section(f"Lid-driven cavity at Re {re} against Ghia et al. (1982)", r, body)

    r = load("benchmarks/conservation.json")
    body = [f"Relative change of total mass: {_sci(r['rel_change'])}."] if r else []
    lines += _section("Mass conservation", r, body)

    r = load("benchmarks/smagorinsky_shear.json")
    body = (
        [
            f"Relative difference between the solver's eddy viscosity and Cs^2 |S| with "
            f"Cs = {r['smagorinsky']}: {_sci(r['rel_error'])}."
        ]
        if r
        else []
    )
    lines += _section("Smagorinsky eddy viscosity in uniform shear", r, body)

    r = load("benchmarks/force_stress.json")
    body = [f"Corrected flux relative to F u: {_sci(r['ratio'])}."] if r else []
    lines += _section("Force correction of the sub-grid stress", r, body)

    r = load("benchmarks/numpy_jax_agreement.json")
    body = []
    if r:
        body = [
            "| Case | Steps | Largest velocity difference |",
            "| --- | --- | --- |",
            *[
                f"| {x['case']} | {x['steps']} | {_pct(x['max_abs_diff_over_uref'], 4)} |"
                for x in r["rows"]
            ],
        ]
    lines += _section("NumPy against JAX", r, body)

    r = load("benchmarks/porous_lambda.json")
    body = []
    if r:
        body = [
            "| λ d | Inflow speed | Momentum balance | λ measured ÷ λ set |",
            "| --- | --- | --- | --- |",
            *[
                f"| {x['lambda_times_depth']} | {x['inflow_speed']} | "
                f"{x['momentum_balance']:.5f} | {x['lambda_ratio']:.4f} |"
                for x in r["rows"]
            ],
            "",
            "The momentum balance checks that the drag is applied as specified. λ by CODASC's "
            "definition also carries the lattice's compressibility error, which shrinks "
            f"{r['error_ratio_halving_u']:.1f} times when the inflow speed halves (expected about "
            "4, as the square of the speed).",
        ]
    lines += _section("Porous block: drag and pressure-loss coefficient", r, body)

    r = load("benchmarks/tracer_conservation.json")
    body = [f"Relative difference: {_sci(r['rel_error'])}."] if r else []
    lines += _section("Tracer conservation with sources and walls", r, body)

    r = load("benchmarks/tracer_pulse.json")
    body = []
    if r:
        body = [
            "| Diffusivity | Velocity | Steps | Relative L2 error |",
            "| --- | --- | --- | --- |",
            *[
                f"| {x['diffusivity']} | ({x['velocity'][0]}, {x['velocity'][1]}) | "
                f"{x['steps']} | {_pct(x['rel_l2'])} |"
                for x in r["rows"]
            ],
        ]
    lines += _section("Tracer pulse against the exact solution", r, body)

    r = load("benchmarks/browser_agreement.json")
    body = []
    if r:
        body = [
            f"GPU adapter: {r['adapter']}.",
            "",
            "| Case | Cells | Steps | CPU worker | WebGPU |",
            "| --- | --- | --- | --- | --- |",
            *[
                f"| {x['name']} | {x['cells']} | {x['steps']} | {_pct(x['cpuError'], 4)} | "
                + ("n/a" if x["gpuError"] is None else _pct(x["gpuError"], 4))
                + " |"
                for x in r["rows"]
            ],
        ]
    lines += _section("Browser solvers against the Python reference", r, body)

    lines += ["## 2. Street physics", ""]
    r = load("street/regimes.json")
    body = []
    if r:
        body = [
            "| H/W | Stacked vortex cells | Strongest vortex | Top of the street ÷ u_ref | "
            "Street floor with the wind |",
            "| --- | --- | --- | --- | --- |",
            *[
                f"| {x['aspect']} | {x['stacked_primary_vortices']} | "
                f"{x.get('strongest_vortex_rotation') or 'none'} | "
                f"{x.get('top_flow_over_uref', float('nan')):+.2f} | "
                f"{_pct(x['floor_fraction_with_wind'], 0)} |"
                for x in r["rows"]
            ],
            "",
            *[
                f"- H/W {c['aspect']}: {c['expectation']}. Observed: {c['observed']}. "
                f"{'Meets' if c['passed'] else '**Misses**'} the expectation."
                for c in r["checks"]
            ],
        ]
    lines += _section("Vortex structure against street aspect ratio", r, body)

    r = load("street/upwind.json")
    body = []
    if r:
        body = [
            "| Streets in the row | Strongest vortex | Top of the street ÷ u_ref |",
            "| --- | --- | --- |",
            *[
                f"| {x['streets_in_row']} | {x['strongest_vortex_rotation']} | "
                f"{x['top_flow_over_uref']:+.2f} |"
                for x in r["rows"]
            ],
            "",
            "With a single street, the vortex shed from the first block's upwind edge stays over "
            "the street and turns its mean vortex the wrong way; the studied street therefore "
            "sits behind one upwind street (docs/solver.md).",
        ]
    lines += _section("A street upwind of the studied street", r, body)

    r = load("street/sponge.json")
    body = []
    if r:
        body = [
            "| Configuration | Mean density spread, second half |",
            "| --- | --- |",
            *[f"| {x['configuration']} | {x['mean_rho_std_second_half']:.4f} |" for x in r["rows"]],
            "",
            f"Noise reduced {r['noise_reduction_factor']:.1f} times. For scale, the pressure "
            f"of a vortex turning at twice the inflow speed corresponds to a density change of "
            f"{r['vortex_pressure_scale']:.4f}.",
        ]
    lines += _section("Absorbing layers against trapped sound", r, body)

    r = load("street/stability.json")
    body = []
    if r:
        body = [
            "| Reynolds number | Cs | Result |",
            "| --- | --- | --- |",
            *[
                f"| {x['reynolds']:.0f} | {x['smagorinsky']} | "
                + ("stable" if x["stable"] else f"blew up by step {x['steps_run']}")
                + " |"
                for x in r["rows"]
            ],
        ]
    lines += _section("Stability of the street solver", r, body)

    lines += ["## 3. Trees, hedges and fumes", ""]
    r = load("trees/calibration.json")
    body = []
    if r:
        body = [
            "| Sc_t | FB | NMSE | FAC2 |",
            "| --- | --- | --- | --- |",
            *[
                f"| {x['schmidt']} | {x['fb']:+.2f} | {x['nmse']:.2f} | {x['fac2']:.2f} |"
                if x.get("healthy")
                else f"| {x['schmidt']} | unstable | | |"
                for x in r["rows"]
            ],
            "",
            f"Kept: Sc_t = {r['schmidt']}, the only calibrated parameter.",
        ]
    lines += _section("Turbulent Schmidt number, calibrated on one case", r, body)

    r = load("trees/codasc.json")
    body = []
    if r:
        crit = r["threshold"]
        body = [
            f"Urban criteria (Hanna and Chang 2012): |FB| < {crit['fb_abs_below']}, "
            f"NMSE < {crit['nmse_below']}, FAC2 > {crit['fac2_above']}.",
            "",
            "| Case | W/H | Stand density | λ (1/m) | FB | NMSE | FAC2 |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            *[
                f"| {x['case']} | {x['aspect_w_over_h']} | {x['stand_density']} | "
                f"{x['lambda_per_m']} | "
                + (
                    f"{x['metrics']['fb']:+.2f} | {x['metrics']['nmse']:.2f} | "
                    f"{x['metrics']['fac2']:.2f} |"
                    if "metrics" in x
                    else "unstable | | |"
                )
                for x in r["rows"]
            ],
        ]
        if r.get("overall"):
            o = r["overall"]
            body += [
                "",
                f"All cases together ({o['n']} points): FB {o['fb']:+.2f}, NMSE {o['nmse']:.2f}, "
                f"FAC2 {o['fac2']:.2f}.",
            ]
    lines += _section("Concentrations against the CODASC wind tunnel", r, body)

    r = load("trees/directions.json")
    body = []
    if r:
        body = [
            "| Case | Expected on the leeward pavement | Leeward ratio | Windward ratio |",
            "| --- | --- | --- | --- |",
            *[
                f"| {x['case']} | {x['expected_leeward']} | {x['ratio']['A']:.2f} | "
                f"{x['ratio']['B']:.2f} |"
                for x in r["rows"]
                if "ratio" in x
            ],
        ]
    lines += _section("Direction of the effect: trees and a hedge", r, body)

    r = load("trees/reynolds.json")
    body = []
    if r:
        body = [
            "| Case | Change, leeward | Change, windward |",
            "| --- | --- | --- |",
            *[
                f"| {x['case']} | {_pct(x['relative_change']['A'], 1)} | "
                f"{_pct(x['relative_change']['B'], 1)} |"
                for x in r["rows"]
                if "relative_change" in x
            ],
        ]
    lines += _section("Reynolds-number sensitivity of pavement exposure", r, body)

    lines += [
        "## Still to come",
        "",
        "2D against 3D (phase 4), sun and heat (phase 3), and the AI's accuracy (phase 4).",
        "",
        "## What the model leaves out",
        "",
        "- 3D effects such as junctions, short streets and wind along the street",
        "- NO-NO2-O3 chemistry (the fumes are a passive tracer)",
        "- Pollution caught by leaves (deposition)",
        "- Cooling by evaporation from leaves",
        "- Buoyancy from sun-heated walls",
        "- Turbulence from moving traffic",
        "- Real-scale Reynolds numbers",
        "- Traffic changing over the day",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m treesvb.validate")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        if not DOC.exists() or DOC.read_text() != text:
            print("docs/validation.md is out of date: run python -m treesvb.validate")
            return 1
        return 0
    DOC.write_text(text)
    print(f"wrote {DOC.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
