"""Generate docs/validation.md from results/*.json (BRIEF.md section 8).

    python -m treesvb.validate          # rewrite docs/validation.md
    python -m treesvb.validate --check  # fail if the committed file is out of date

Every number in the document is read from a result file; nothing is typed by hand.
"""

from __future__ import annotations

import argparse
import json
import re as regex
import sys

from .results import REPO, RESULTS

APP = REPO / "apps" / "web" / "src"

DOC = REPO / "docs" / "validation.md"

UNSTABLE = "unstable (the run blew up)"
SETTLING_NOTE = (
    "Settling: the relative difference between the averages over the first and the second half "
    "of the averaging window, the largest of the two pavements and the street mean. A difference "
    "between two cases smaller than their settling is not meaningful."
)


def _load(rel: str) -> dict | None:
    p = RESULTS / rel
    return json.loads(p.read_text()) if p.exists() else None


def _pct(v: float, digits: int = 2) -> str:
    return f"{100 * v:.{digits}f}%"


def _sci(v: float) -> str:
    return f"{v:.1e}"


def _verdict(r: dict | None, target: bool = True) -> str:
    if r is None:
        return "not yet computed"
    if not target:
        return "for information, no target"
    return "meets the target" if r["passed"] else "**misses the target**"


def _provenance(r: dict) -> str:
    return (
        f"_Source: `results/{r['_path']}`, generated {r['generated_at']} by "
        f"`{r['generated_by']}` at commit `{r['commit'][:7]}`._"
    )


def _section(title: str, r: dict | None, body: list[str], target: bool = True) -> list[str]:
    out = [f"### {title}", "", f"Verdict: {_verdict(r, target)}.", ""]
    if r is None:
        return [*out, "Not yet computed.", ""]
    if r.get("method"):
        out += [f"Method: {r['method'].rstrip('.')}.", ""]
    out += body
    out += ["", _provenance(r), ""]
    return out


def _regime_body(r: dict) -> list[str]:
    return [
        "| H/W | Stacked vortex cells | Strongest vortex | Top of the street ÷ u_ref | "
        "Street floor with the wind |",
        "| --- | --- | --- | --- | --- |",
        *[
            f"| {x['aspect']} | {x['stacked_primary_vortices']} | "
            f"{x.get('strongest_vortex_rotation') or 'none'} | "
            f"{x.get('top_flow_over_uref', float('nan')):+.2f} | "
            f"{_pct(x['floor_fraction_with_wind'], 0)} |"
            for x in r["rows"]
        ],
        "",
        *[
            f"- H/W {c['aspect']}: {c['expectation']}. Observed: {c['observed']}. "
            f"{'Meets' if c['passed'] else '**Misses**'} the expectation."
            for c in r["checks"]
        ],
    ]


def _ratios(measured: dict, model: dict, wall: str) -> list[float]:
    return [b / a for a, b in zip(measured[wall], model[wall], strict=True)]


def render() -> str:
    def load(rel):
        r = _load(rel)
        if r is not None:
            r["_path"] = rel
        return r

    lines = [
        "# Validation",
        "",
        "Generated by `python -m treesvb.validate` from `results/*.json`. Do not edit by hand; "
        "rerun the command after the results change. Every model number here is simulated.",
        "",
        "## 1. Solver benchmarks",
        "",
    ]

    r = load("benchmarks/poiseuille.json")
    body = []
    if r:
        body = [
            f"Target: relative L2 error below {_pct(r['threshold']['rel_l2_below'], 0)} with "
            f"{r['threshold']['for_height_at_least']} cells across or more.",
            "",
            "| Cells across | Relative L2 error | Steps |",
            "| --- | --- | --- |",
            *[f"| {x['height']} | {_pct(x['rel_l2'], 3)} | {x['steps']} |" for x in r["rows"]],
            "",
            f"Observed order of convergence: {r['observed_order']:.2f}.",
        ]
    lines += _section("Channel flow against the exact Poiseuille profile", r, body)

    for re in (100, 1000):
        r = load(f"benchmarks/cavity_re{re}.json")
        body = []
        if r:
            cu, cv = r["u_vertical_centreline"], r["v_horizontal_centreline"]
            body = [
                f"Target: within {_pct(r['threshold']['max_abs_error_below'], 0)} of the lid "
                f"speed at every tabulated point. Grid {r['grid']} x {r['grid']}, "
                f"{r['steps']} steps.",
                "",
                "| Profile | Largest difference | RMS difference |",
                "| --- | --- | --- |",
                f"| u on the vertical centreline | {_pct(cu['max_abs_error'])} | "
                f"{_pct(cu['rms_error'])} |",
                f"| v on the horizontal centreline | {_pct(cv['max_abs_error'])} | "
                f"{_pct(cv['rms_error'])} |",
                "",
                f"Reference: {r['reference']['citation']}; values via "
                f"{r['reference'][f're{re}_via']}.",
            ]
        lines += _section(f"Lid-driven cavity at Re {re} against Ghia et al. (1982)", r, body)

    r = load("benchmarks/conservation.json")
    body = [f"Relative change of total mass: {_sci(r['rel_change'])}."] if r else []
    lines += _section("Mass conservation", r, body)

    r = load("benchmarks/smagorinsky_shear.json")
    body = (
        [
            f"Relative difference between the solver's eddy viscosity and Cs^2 |S| with "
            f"Cs = {r['smagorinsky']}: {_sci(r['rel_error'])}."
        ]
        if r
        else []
    )
    lines += _section("Smagorinsky eddy viscosity in uniform shear", r, body)

    r = load("benchmarks/force_stress.json")
    body = [f"Corrected flux relative to F u: {_sci(r['ratio'])}."] if r else []
    lines += _section("Force correction of the sub-grid stress", r, body)

    r = load("benchmarks/numpy_jax_agreement.json")
    body = []
    if r:
        body = [
            "| Case | Steps | Largest velocity difference |",
            "| --- | --- | --- |",
            *[
                f"| {x['case']} | {x['steps']} | {_pct(x['max_abs_diff_over_uref'], 4)} |"
                for x in r["rows"]
            ],
        ]
    lines += _section("NumPy against JAX", r, body)

    r = load("benchmarks/porous_lambda.json")
    body = []
    if r:
        body = [
            "| λ d | Inflow speed | Momentum balance | λ measured ÷ λ set |",
            "| --- | --- | --- | --- |",
            *[
                f"| {x['lambda_times_depth']} | {x['inflow_speed']} | "
                f"{x['momentum_balance']:.5f} | {x['lambda_ratio']:.4f} |"
                for x in r["rows"]
            ],
            "",
            "The momentum balance checks that the drag is applied as specified. λ by CODASC's "
            "definition also carries the lattice's compressibility error, which shrinks "
            f"{r['error_ratio_halving_u']:.1f} times when the inflow speed halves (expected about "
            "4, as the square of the speed).",
        ]
    lines += _section("Porous block: drag and pressure-loss coefficient", r, body)

    r = load("benchmarks/tracer_conservation.json")
    body = [f"Relative difference: {_sci(r['rel_error'])}."] if r else []
    lines += _section("Tracer conservation with sources and walls", r, body)

    r = load("benchmarks/tracer_pulse.json")
    body = []
    if r:
        body = [
            "| Diffusivity | Velocity | Steps | Relative L2 error |",
            "| --- | --- | --- | --- |",
            *[
                f"| {x['diffusivity']} | ({x['velocity'][0]}, {x['velocity'][1]}) | "
                f"{x['steps']} | {_pct(x['rel_l2'])} |"
                for x in r["rows"]
            ],
        ]
    lines += _section("Tracer pulse against the exact solution", r, body)

    r = load("benchmarks/browser_agreement.json")
    body = []
    if r:
        body = [
            f"GPU adapter: {r['adapter']}.",
            "",
            "| Case | Cells | Steps | CPU worker | WebGPU |",
            "| --- | --- | --- | --- | --- |",
            *[
                f"| {x['name']} | {x['cells']} | {x['steps']} | {_pct(x['cpuError'], 4)} | "
                + ("n/a" if x["gpuError"] is None else _pct(x["gpuError"], 4))
                + " |"
                for x in r["rows"]
            ],
        ]
    lines += _section("Browser solvers against the Python reference", r, body)

    lines += ["## 2. Street physics", ""]
    r = load("street/regimes.json")
    lines += _section(
        "Vortex structure against street aspect ratio", r, _regime_body(r) if r else []
    )

    r = load("street/regimes_h48.json")
    title = "Deep streets on a finer grid"
    if r:
        title = f"Deep streets at {r['rows'][0]['height_cells']} cells per building height"
    lines += _section(title, r, _regime_body(r) if r else [])

    r = load("street/upwind.json")
    body = []
    if r:
        body = [
            "| H/W | Streets in the row | Studied street from the row's edge (H) | Top vortex | "
            "Top of the street ÷ u_ref |",
            "| --- | --- | --- | --- | --- |",
            *[
                f"| {x['aspect']} | {x['streets_in_row']} | {x['leading_edge_to_street_h']:.1f} | "
                f"{x['top_vortex_rotation']} | {x['top_flow_over_uref']:+.2f} |"
                for x in r["rows"]
            ],
            "",
            "Close to the row's upwind edge, the vortex shed from the first block stays over the "
            "street and turns its mean vortex the wrong way; the studied street therefore starts "
            "at least 3 H behind the edge (docs/solver.md).",
        ]
    lines += _section("Streets upwind of the studied street", r, body)

    r = load("street/sponge.json")
    body = []
    if r:
        body = [
            "| Configuration | Mean density spread, second half |",
            "| --- | --- |",
            *[
                f"| {x['configuration']} | {x['mean_rho_std_second_half']:.4f} |"
                if "mean_rho_std_second_half" in x
                else f"| {x['configuration']} | {UNSTABLE} at step {x['failed_at']} |"
                for x in r["rows"]
            ],
            "",
            (
                f"Noise reduced {r['noise_reduction_factor']:.1f} times."
                if r["noise_reduction_factor"] is not None
                else "Without the layers the noise grows until the run fails."
            )
            + " For scale, the pressure of a vortex turning at twice the inflow speed "
            f"corresponds to a density change of {r['vortex_pressure_scale']:.4f}.",
        ]
    lines += _section("Absorbing layers against trapped sound", r, body)

    r = load("street/stability.json")
    body = []
    if r:
        body = [
            "| Reynolds number | Cs | Result |",
            "| --- | --- | --- |",
            *[
                f"| {x['reynolds']:.0f} | {x['smagorinsky']} | "
                + ("stable" if x["stable"] else f"blew up by step {x['steps_run']}")
                + " |"
                for x in r["rows"]
            ],
        ]
    lines += _section("Stability of the street solver", r, body)

    def trees_sections(suffix: str, label: str) -> list[str]:
        out: list[str] = []
        r = load(f"trees/calibration{suffix}.json")
        body = []
        if r:
            body = [
                "| Sc_t | FB | NMSE | FAC2 |",
                "| --- | --- | --- | --- |",
                *[
                    f"| {x['schmidt']} | {x['fb']:+.2f} | {x['nmse']:.2f} | {x['fac2']:.2f} |"
                    if x.get("healthy")
                    else f"| {x['schmidt']} | unstable | | |"
                    for x in r["rows"]
                ],
                "",
                f"Kept: Sc_t = {r['schmidt']}, the only calibrated parameter.",
            ]
            tried = [x["schmidt"] for x in r["rows"] if x.get("healthy")]
            if r["schmidt"] in (min(tried), max(tried)):
                end = "smallest" if r["schmidt"] == min(tried) else "largest"
                body += [
                    "",
                    f"It is the {end} value tried, so the best value may lie outside the range.",
                ]
        out += _section("Turbulent Schmidt number, calibrated on one case" + label, r, body)

        r = load(f"trees/codasc{suffix}.json")
        body = []
        if r:
            crit = r["threshold"]
            body = [
                f"Urban criteria (Hanna and Chang 2012): |FB| < {crit['fb_abs_below']}, "
                f"NMSE < {crit['nmse_below']}, FAC2 > {crit['fac2_above']}.",
                "",
                "| Case | W/H | Stand density | λ (1/m) | FB | NMSE | FAC2 | Settling |",
                "| --- | --- | --- | --- | --- | --- | --- | --- |",
                *[
                    f"| {x['case']} | {x['aspect_w_over_h']} | {x['stand_density']} | "
                    f"{x['lambda_per_m']} | "
                    + (
                        f"{x['metrics']['fb']:+.2f} | {x['metrics']['nmse']:.2f} | "
                        f"{x['metrics']['fac2']:.2f} | "
                        + (_pct(x["settling"], 0) if "settling" in x else "not measured")
                        + " |"
                        if "metrics" in x
                        else f"{UNSTABLE} | | | |"
                    )
                    for x in r["rows"]
                ],
            ]
            if any("settling" in x for x in r["rows"]):
                body += ["", SETTLING_NOTE]
            if r.get("overall"):
                o = r["overall"]
                ran = sum("metrics" in x for x in r["rows"])
                which = (
                    "All cases together"
                    if ran == len(r["rows"])
                    else f"The {ran} of {len(r['rows'])} cases that ran, together"
                )
                body += [
                    "",
                    f"{which} ({o['n']} points): FB {o['fb']:+.2f}, "
                    f"NMSE {o['nmse']:.2f}, FAC2 {o['fac2']:.2f}.",
                ]
            heights = " | ".join(f"z/H {z:.2f}" for z in r["heights"])
            body += [
                "",
                "Model ÷ wind tunnel at each tap height (wall A leeward, wall B windward):",
                "",
                f"| Case | Wall | {heights} |",
                "| --- | --- |" + " --- |" * len(r["heights"]),
                *[
                    f"| {x['case']} | {w} | "
                    + " | ".join(f"{v:.2f}" for v in _ratios(x["measured"], x["model"], w))
                    + " |"
                    for x in r["rows"]
                    if "model" in x
                    for w in "AB"
                ],
            ]
        out += _section("Concentrations against the CODASC wind tunnel" + label, r, body)

        r = load(f"trees/directions{suffix}.json")
        body = []
        if r:
            body = [
                "| Case | Expected on the leeward pavement | Leeward ratio | Windward ratio |",
                "| --- | --- | --- | --- |",
                *[
                    f"| {x['case']} | {x['expected_leeward']} | {x['ratio']['A']:.2f} | "
                    f"{x['ratio']['B']:.2f} |"
                    if "ratio" in x
                    else f"| {x['case']} | | {UNSTABLE} | |"
                    for x in r["rows"]
                ],
            ]
        out += _section("Direction of the effect: trees and a hedge" + label, r, body)

        r = load(f"trees/reynolds{suffix}.json")
        body = []
        if r:
            body = [
                "| Case | Change, leeward | Change, windward |",
                "| --- | --- | --- |",
                *[
                    f"| {x['case']} | {_pct(x['relative_change']['A'], 1)} | "
                    f"{_pct(x['relative_change']['B'], 1)} |"
                    if "relative_change" in x
                    else f"| {x['case']} | {UNSTABLE} | |"
                    for x in r["rows"]
                ],
            ]
        out += _section("Reynolds-number sensitivity of pavement exposure" + label, r, body)

        r = load(f"trees/resolution{suffix}.json")
        body = []
        if r:
            body = [
                "| Case | Cells per H | FB | NMSE | FAC2 | Lowest tap A ÷ tunnel | "
                "Lowest tap B ÷ tunnel |",
                "| --- | --- | --- | --- | --- | --- | --- |",
                *[
                    f"| {x['case']} | {k[1:]} | {x[k]['metrics']['fb']:+.2f} | "
                    f"{x[k]['metrics']['nmse']:.2f} | {x[k]['metrics']['fac2']:.2f} | "
                    f"{_ratios(x['measured'], x[k]['model'], 'A')[0]:.2f} | "
                    f"{_ratios(x['measured'], x[k]['model'], 'B')[0]:.2f} |"
                    if "metrics" in x[k]
                    else f"| {x['case']} | {k[1:]} | {UNSTABLE} | | | | |"
                    for x in r["rows"]
                    for k in sorted((k for k in x if k.startswith("h")), key=lambda k: int(k[1:]))
                ],
            ]
        # The finer grids skip the resolution study (it would need twice their grid again).
        if r or not suffix:
            out += _section("Grid resolution of the comparison" + label, r, body, target=False)
        return out

    lines += ["## 3. Trees, hedges and fumes", ""]
    # Plain names hold the CPU engine's grid; other grids carry a suffix such as _h48.
    finer = sorted(
        (
            p.stem.removeprefix("calibration")
            for p in (RESULTS / "trees").glob("calibration_h*.json")
        ),
        key=lambda x: int(x[2:]),
    )
    lines += trees_sections("", "")
    for suffix in finer:
        lines += trees_sections(suffix, f" ({int(suffix[2:])} cells per building height)")

    if load("trees/codasc.json"):
        lines += [
            "What these results show, and what they do not: `docs/codasc.md`, section "
            '"Results of the first comparison".',
            "",
        ]

    lines += ai_sections(load)
    lines += [
        "## Still to come",
        "",
        "2D against 3D (phase 4).",
        "",
        "## What the model leaves out",
        "",
        "The same list as the app's How we know screen (`apps/web/src/content/leftOut.ts`).",
        "",
        *[f"- {item}" for item in left_out()],
        "",
    ]
    return "\n".join(lines)


def left_out() -> list[str]:
    """The app's list of what the model leaves out, in English, in the app's order."""
    keys = regex.findall(r"'(leftOut\.[A-Za-z0-9]+)'", (APP / "content" / "leftOut.ts").read_text())
    strings = json.loads((APP / "i18n" / "en.json").read_text())
    return [strings[k] for k in keys]


def _scores_row(label: str, s: dict) -> str:
    return (
        f"| {label} | {s['n']} | {s['r2']:.3f} | {_pct(s['median_relative_error'], 1)} | "
        f"{s['fac2']:.3f} |"
    )


def ai_sections(load) -> list[str]:
    """Section 4: the dataset and the surrogate's scores, once they exist."""
    out = ["## 4. The AI", ""]
    d = load("dataset/summary.json")
    body = []
    if d:
        run = d["plan"]["run"]
        body = [
            f"{d['train_runs']} training runs; {run['spin_up']} steps of spin-up and "
            f"{run['average']} averaged per run; "
            f"{d['cell_updates_per_second'] / 1e9:.2f} billion cell updates per second.",
            "",
            "| Block | Runs | Healthy | Trees | Hedge | Bare | Still filling (trees) |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            *[
                f"| {k} | {c['runs']} | {c['healthy']} | {c['trees']} | {c['hedge']} | "
                f"{c['none']} | {c['still_filling']['trees']} |"
                for k, c in d["blocks"].items()
            ],
            "",
            "How much the pavement averages still move between the halves of a run (median and "
            f"90th percentile of the half difference over the sum): exposure "
            f"{_pct(d['noise']['exposure']['median'], 1)} and "
            f"{_pct(d['noise']['exposure']['p90'], 1)}, wind "
            f"{_pct(d['noise']['wind']['median'], 1)} and {_pct(d['noise']['wind']['p90'], 1)}."
            if d.get("noise")
            else "",
        ]
    out += _section("Training data", d, body, target=False)

    m = load("surrogate/metrics.json")
    body = []
    if m:
        t = m["targets"]
        body = [
            f"Targets: R² at least {t['r2']}, median relative error at most "
            f"{_pct(t['median_relative_error'], 0)}, FAC2 at least {t['fac2']}, on pavement "
            f"exposure in the test block. Met: {'yes' if m['meets_targets'] else '**no**'}.",
            "",
            "| Set and quantity | Runs | R² | Median relative error | FAC2 |",
            "| --- | --- | --- | --- | --- |",
        ]
        for name, label in (("test", "Test"), ("ood", "Out of distribution")):
            s = m["scalar"][name]
            body += [
                _scores_row(f"{label}: pavement exposure", s["exposure"]),
                _scores_row(f"{label}: fumes against the bare street, leeward", s["ratio_A"]),
                _scores_row(f"{label}: fumes against the bare street, windward", s["ratio_B"]),
                _scores_row(f"{label}: pavement wind, leeward", s["wind_A"]),
                _scores_row(f"{label}: pavement wind, windward", s["wind_B"]),
            ]
        s = m["scalar"]["test"]
        body += [
            "",
            "The solver's own averages limit these scores: a perfect model would show a median "
            f"relative error of about {_pct(s['noise_floor']['exposure'], 1)} on exposure and "
            f"{_pct(s['noise_floor']['wind'], 1)} on wind against the test labels (half "
            "difference over the sum of the two halves of each run). The test labels fall "
            "within the ensemble's two standard deviations in "
            f"{_pct(s['within_two_spreads_A'], 0)} (leeward) and "
            f"{_pct(s['within_two_spreads_B'], 0)} (windward) of runs. The guard accepts "
            f"{_pct(s['guard_accepts'], 0)} of the test designs and "
            f"{_pct(m['scalar']['ood']['guard_accepts'], 0)} of the out-of-distribution ones.",
            "",
            "| Field model | Runs | R² of log(1 + c⁺) | R² of wind speed |",
            "| --- | --- | --- | --- |",
            *[
                f"| {label} | {m['field'][k]['runs']} | {m['field'][k]['r2_log1p_cplus']:.3f} | "
                f"{m['field'][k]['r2_speed']:.3f} |"
                for k, label in (("test", "Test"), ("ood", "Out of distribution"))
            ],
            "",
            "| Model file | Size |",
            "| --- | --- |",
            *[
                f"| `{name}` | {v['bytes'] / 1024 / 1024:.2f} MB |"
                for name, v in m["models"].items()
            ],
        ]
    # The verdict is the brief's accuracy targets (BRIEF.md 7.3), not the file's own pass flag,
    # which only checks the model sizes.
    verdict = {**m, "passed": m["meets_targets"]} if m else None
    out += _section("Surrogate accuracy against the BRIEF.md 7.3 targets", verdict, body)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m treesvb.validate")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        if not DOC.exists() or DOC.read_text() != text:
            print("docs/validation.md is out of date: run python -m treesvb.validate")
            return 1
        return 0
    DOC.write_text(text)
    print(f"wrote {DOC.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
