"""Port the UTCI polynomial of pythermalcomfort to TypeScript (apps/web/src/sun/utciPolynomial.ts).

    .venv-ref/bin/python scripts/port_utci.py

Reads pythermalcomfort/models/utci.py (_utci_optimized) from the installed package and rewrites
each term with the same coefficients and the same order of operations, so the port gives the
same doubles. The generated file carries pythermalcomfort's MIT licence notice.
"""

from __future__ import annotations

import re
from importlib import metadata, util
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "apps" / "web" / "src" / "sun" / "utciPolynomial.ts"
NAMES = {"tdb": "ta", "v": "va", "delta_t_tr": "dtr", "pa": "pa"}


def terms() -> list[str]:
    text = Path(util.find_spec("pythermalcomfort.models.utci").origin).read_text()
    body = text[text.index("def _utci_optimized(") :]
    body = body[body.index("return (") + len("return (") :]
    body = body[: body.index("\n    )\n")]
    out = []
    for line in body.strip().splitlines():
        t = line.strip()
        if not t:
            continue
        t = re.sub(r"\(10 \*\* \(-(\d+)\)\)", r"1e-\1", t)
        t = re.sub(r"\b(tdb|v|delta_t_tr|pa)\b", lambda m: NAMES[m.group(1)], t)
        if "**" in t:
            raise SystemExit(f"unexpected power in: {line}")
        out.append(t)
    return out


def main() -> None:
    licence = Path(
        metadata.distribution("pythermalcomfort").locate_file(
            f"pythermalcomfort-{metadata.version('pythermalcomfort')}.dist-info/licenses/LICENSE"
        )
    ).read_text()
    lines = terms()
    expr = "\n".join(f"    {t}" for t in lines)
    notice = "\n".join(f" * {x}".rstrip() for x in licence.strip().splitlines())
    version = metadata.version("pythermalcomfort")
    OUT.write_text(
        f"""// Generated by scripts/port_utci.py from pythermalcomfort {version}
// (models/utci.py, _utci_optimized); do not edit by hand.
//
// The operational UTCI polynomial of Broede et al. (2012), as implemented in pythermalcomfort:
/*
{notice}
 */

// prettier-ignore

/**
 * UTCI in degrees C from air temperature ta (C), wind speed at 10 m va (m/s), mean radiant
 * temperature minus air temperature dtr (K) and water vapour pressure pa (kPa).
 */
export function utciPolynomial(ta: number, va: number, dtr: number, pa: number): number {{
  return (
{expr}
  );
}}
"""
    )
    print(f"wrote {OUT} ({len(lines)} terms)")


if __name__ == "__main__":
    main()
